[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "rxnfp"
dynamic = ["version"]
description = "chemical reaction fingerprints"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{name = "Philippe Schwaller", email = "phs@zurich.ibm.com"}]
keywords = ['chemical', 'reactions', 'fingerprints', 'classification']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 2 - Pre-Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = ['transformers>=4.5.0', 'torch>=1.6', 'scipy>=1.7.0', 'scikit-learn>=1.0', 'matplotlib>=3.5.0', 'faerun>=0.3.20']

[project.optional-dependencies]
tmap = ['tmap>=1.2.1']

[project.urls]
Repository = "https://github.com/rxn4chemistry/rxnfp/tree/master/"
Documentation = "https://rxn4chemistry.github.io/rxnfp/"

[project.entry-points.nbdev]
rxnfp = "rxnfp._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "rxnfp.__version__"}

[tool.setuptools.packages.find]
include = ["rxnfp"]

[tool.nbdev]
doc_path = 'docs'
branch = 'master'
tst_flags = 'data|cuda|slow|optional'
custom_sidebar = true
title = 'rxnfp'
